language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: C5PDLRBnypcx44UYfgy7dlx9RyrhFIXYque3CCtCfTS3jC02HfSTrXMXR4mEPW378Rly+Rtw0OlE+XV05kDEXZ85aEzpiiLIyavVrgjtWQSHNJsToUVLamFEF44ad93Q3ZnBg/KiqtwblMZo1ue9w3lTASiFbKW949WwFkWvur7lJcoX42qeneYq0Y2486bv/gu3V+2t5RyI+MdYt8D7ttCKHrxiNzbtU4pMjp39nRJannWEw1oXOpilB1J7CVRRTD7bR8iatbdZkRl2CF7i4QayV/j/mjTingMUAKRAtG728qzoCmc3sc4F+tqBPP1aS/TYrDLtfDI+7atUgrZ2o8pF4squ+3FasGAVnjmUHTnwrxlwtmAyKfHU2L7uay9ixSLy29aHB9JiMaXTrVBmXLsOmC2ItuK0AbNmDw+meZiSoIJM7Ehp2zx1z4o+NHnLTkUUgsEepLmknWnQzSpCQ6/rKxdLrRiPQEFumHpzoMjMjvfsOapSi4x0rKyu9XhBo7PeLr7P+UC1aUOM4cJnB6bVDh+YTcqJptS2Zh017oYZwv4tRw5lVBMPV4mklqfkN2uoQwzLptDlF0dJ5ajh16qo924AKhhBuzF+Nmouhd+KhuPGI+8TV/HcL8ROAp8sAjHwIRHFBIl9uqIFlJBKBxxoUgFpoFMgKwmRHrzECVw=
  file:
    - 'hast-util-select.js'
    - 'hast-util-select.min.js'
  on:
    tags: true
